Jc-2
JRM-JACP/ProcessingService pull request #1
Opened 2023-08-23 12:36 UTC by freesky15

2023-08-23 12:38 UTC, saffchen commented
Please change target branch

2023-08-23 13:30 UTC, pelmegov requested changes

2023-08-23 13:30 UTC, pelmegov commented on Dockerfiles/Dockerfile
> +FROM openjdk:11
Why not 17th?

2023-08-23 13:30 UTC, pelmegov commented on src/main/java/org/jrmjacp/processingservice/utils/DockerProcessing.java
> +
Setup autoformatting before commit.

2023-08-24 05:31 UTC, closed without merging

2023-08-24 05:32 UTC, freesky15 commented
Done!